# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvLrxtvdbzXmo9CtABYgpcd8pyvID58J
"""

def boyer_moore(text, pat):

  def skip_table(pattern):
    table = {}
    for i in range(len(pattern) - 1):
        table[pattern[i]] = len(pattern) - 1 - i

    return table

  skip = skip_table(pat)
  pat_len = len(pat)
  text_len = len(text)
  i = 0

  while i <= text_len - pat_len:
    j = pat_len - 1
    while j >= 0 and pat[j] == text[i + j]:
        j -= 1
    if j < 0:
        return i
    else:
        if text[i + j] in skip:
            i += skip[text[i + j]]
        else:
            i += 1

  return None

text = "I AM ALWAYS BEAUTIFUL"
pat = "ALWAYS"

result = boyer_moore(text, pat)

print(result)