# -*- coding: utf-8 -*-
"""Count_pattern_matches.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZX-C3iC67R_Xo91M1w2OkNsoqSCcyNU
"""

def is_prefix(text, p):
  return all(p[i] == text[i] for i in range(len(p)))

def is_suffix(text, p):
  len_text = len(text)
  len_p = len(p)
  return all(p[i] == text[len_text - len_p + i] for i in range(len(p)))

def sigma(text, p):
  print(p)
  if is_suffix(text, p):
    return len(p)
  else:
    return sigma(text, p[:-1])

text = "abbababacacacabacab"
p = "acabh"


print(sigma(text, p))