# -*- coding: utf-8 -*-
"""Naive_algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORU5gSGKDpvHbhLomEJ-EM3nLSkTQAVj
"""

def naive_algorithm(text, pat):
  len_text = len(text)
  len_pat = len(pat)
  j = 0
  idx = []
  for i in range(len_text - len_pat + 1):
    if text[i] == pat[j]:
      for k in range(1, len_pat):
        if text[i+k] != pat[j+k]:
          break
      else:
        idx.append(i)

  return idx

text = "AABAACAADAABAAABAA"
pat = "AABA"
print(naive_algorithm(text, pat))